### ISSUE TITLE
Development improvement update

### ISSUE THREAD

**Issue by Nirjonadda** [McAtze/-ITM-CheveretoIntegration#1]
Please do you have any issue using full title name for folder? If so no then please update folder name to `CheveretoIntegration ` from `ChevInt` So we can better understanding about this folder.

Also no need adding Version no in option title, So please update setting option title to `Chevereto Integration` from `Chevereto Integration 2.0`

Thanks

**Comment by McAtze** [comment]
I think about it.

**Comment by McAtze** [comment]
> Please do you have any issue using full title name for folder? If so no then please update folder name to CheveretoIntegration from ChevInt So we can better understanding about this folder.

As designed..

> Also no need adding Version no in option title, So please update setting option title to Chevereto Integration from Chevereto Integration 2.0

Is changed..

**Comment by Nirjonadda** [comment]
> As designed..

Then I am not going to use your this type design because you should make add-on folder suitable and understandable.

What does your problem with folder name `CheveretoIntegration` ? I did not think you can understanding about folder name `ChevInt` after some month later.

OK this my own opinion. I am wait other developer XF2 support release.

**Comment by McAtze** [comment]
@Nirjonadda Just for you i redesigned the add-on.

Feel free to use it or leave it.. ;)

**Comment by Nirjonadda** [comment]
Sorry for that, I am now going to use your add-on. Thanks
