### ISSUE TITLE
Upload button position misplaced

### ISSUE THREAD

**Issue by amaridev** [McAtze/-ITM-CheveretoIntegration#10]
![screen shot 2018-08-10 at 15 54 36](https://user-images.githubusercontent.com/13658668/43961675-ec2a2a00-9cb5-11e8-83ac-68c2df41d8b4.png)

The upload button is always bad positioned no matter which setting I choose. The **before** option sets the button on top of the editor box. The **after** below and the option to set the Upload button inside the editor toolbar results in two buttons which will disappear as soon as I scroll or click something.

**Comment by McAtze** [comment]
I couldn't confirm the issue. Do you have more information like browser, XF version, etc..

![2018-08-16_16-36-22](https://user-images.githubusercontent.com/8874582/44218058-2f364280-a179-11e8-99b8-eac0da8af777.png)
![2018-08-16_16-37-18](https://user-images.githubusercontent.com/8874582/44218061-2f364280-a179-11e8-8f13-b4018d39f7cb.png)
![2018-08-16_16-38-03](https://user-images.githubusercontent.com/8874582/44218063-2fced900-a179-11e8-997e-2b7bbe2939c4.png)

**Comment by techinnov-974** [comment]
Hello Big bug svg > http://prntscr.com/mp2kl7

**Comment by McAtze** [comment]
Fixed in latest version..
