### ISSUE TITLE
Button does not show

### ISSUE THREAD

**Issue by b33z** [McAtze/-ITM-CheveretoIntegration#11]
Cannot for the life me get the image upload button to show in the toolbar or by the attachments button. Not at all sure why not..

xF - v2.1.5
Chev - v3.12.5
Plugin - v2.0.5

**Comment by McAtze** [comment]
This isn't a bug. Did you check the permissions for the special user group?

![Screenshot 2019-12-21 14 29 31](https://user-images.githubusercontent.com/8874582/71308547-500e4800-23fe-11ea-9d03-13a82387f907.png)

**Comment by b33z** [comment]
Yes, the permissions were enabled. Really not sure why it wasn't working, but I wanted to do a fresh xF install anyway so I went ahead and did that before then installed my style, addons, etc. I then installed your addon and its working great! well done! I think for me it was a piece of custom code or another addon interfering. all good now tho!

thanks for your work and thanks for your time!!

-b

**Comment by b33z** [comment]
UPDATE:
not working at first, then i got it working, now back to not working. pretty sure its something to do with custom style and/or addons. will report more when i know more.

note: i re-opened the issue, but you can close it if you prefer.

thanks again for your time and work!!

**Comment by McAtze** [comment]
It works an default style. If you have any custom style issues, you should ask for helping.
