### ISSUE TITLE
An update for forums with "Attach files" disabled

### ISSUE THREAD

**Issue by Nirjonadda** [McAtze/-ITM-CheveretoIntegration#12]
@McAtze Please can you add TS support for this support: https://chevereto.com/community/threads/xenforo-2-1-support.11552/#post-62265

**Comment by Nirjonadda** [comment]
Also this addon supported show Upload button without enable can upload Attachment.

https://xenforo.com/community/resources/upload-host-images-on-your-forum-using-add-pics-for-free.7698/updates

**Comment by McAtze** [comment]
I will take a look in it..

**Comment by Nirjonadda** [comment]
Use `Regular expression` for `Template modifications`. So this will compatibility for third party styles.

**Comment by Nirjonadda** [comment]
@McAtze Any update please?

**Comment by McAtze** [comment]
> @McAtze Please can you add TS support for this support: https://chevereto.com/community/threads/xenforo-2-1-support.11552/#post-62265

I don't know what do you mean?

**Comment by McAtze** [comment]
> Also this addon supported show Upload button without enable can upload Attachment.
> 
> https://xenforo.com/community/resources/upload-host-images-on-your-forum-using-add-pics-for-free.7698/updates

Implemented in v2.0.6

**Comment by McAtze** [comment]
> Use `Regular expression` for `Template modifications`. So this will compatibility for third party styles.

Not needed. I refered to closing `</head>` tag, so every style should have an closing `</head>` tag
