### ISSUE TITLE
Button position before attachments 

### ISSUE THREAD

**Issue by Nirjonadda** [McAtze/-ITM-CheveretoIntegration#13]
Please can you add one more Button position before attachments? Also when used Button position Before then this should be show before Post reply button.

![ScreenShot00357](https://user-images.githubusercontent.com/6899856/81980801-8f4c6800-962f-11ea-8e41-52b454409263.png)

**Comment by McAtze** [comment]
I **HAD** to pick the preview-button as sibling, because this is the only button in every editor template. So i had a simple code without hidden issues.
I couldn't use before attachments, because when attachments are not allowed or enabled, there is no button as sibling to set the chevereto button.
