### ISSUE TITLE
XenForo 2.2

### ISSUE THREAD

**Issue by Jack-the-Ripper-district-londonien-1888** [McAtze/-ITM-CheveretoIntegration#15]
hello, would it be possible to make it compatible with the new version of XenForo 2.2 beta 1

what are the difference to use the plugin or directly your https://demo.chevereto.com/upload compared to other add-ons that it uses the 2 URLs of the plugin to work

Chevereto software jquery path //demo.chevereto.com/sdk/pup.js
Image upload path https://demo.chevereto.com/upload

**Comment by McAtze** [comment]
> hello, would it be possible to make it compatible with the new version of XenForo 2.2 beta 1

If it is necessary and XF 2.2 is released.

> what are the difference to use the plugin or directly your https://demo.chevereto.com/upload compared to other add-ons that it uses the 2 URLs of the plugin to work

I don't know what your mean. I just simplify the integration of the PUP into XenForo. You need your own Chevereto installation.
