### ISSUE TITLE
updated add-on for Xenforo 2.2

### ISSUE THREAD

**Issue by Jack-the-Ripper-district-londonien-1888** [McAtze/-ITM-CheveretoIntegration#16]
Hello I would like to know if it would be possible to release the version compatible with Xenforo 2.2 Final version thank you

**Comment by McAtze** [comment]
Why should this add-on be not compatible with XF2.2?
What is not working. I mean this add-on and not the PUP.js

**Comment by Jack-the-Ripper-district-londonien-1888** [comment]
hello no it doesn't work anymore the sound button is no longer displayed because the text editor has been changed.

so the buttons are more displayed for uploading an image

XenForo 2.2 he uses https://froala.com/wysiwyg-editor/

**Comment by McAtze** [comment]
Take a look at the new release and give it a try.
