### ISSUE TITLE
This is great does exactly what I've been looking for..
I understand how the query came up object to place new object next to it..

Slight bug..

### ISSUE THREAD

**Issue by r3dn1nja75** [McAtze/-ITM-CheveretoIntegration#19]
Trying to get this working  with editor button fo post_edit and post_edit_new_post 

Working pretty much everywhere else .  

Not playing nice :(

**Comment by McAtze** [comment]
I need a little bit more information to understand your problem. Is it working or is it not workin?

Some Screenshots please
