### ISSUE TITLE
Usergroup permissions

### ISSUE THREAD

**Issue by Nirjonadda** [McAtze/-ITM-CheveretoIntegration#2]
Please canyou add Usergroup permissions "Can use Chevereto Plugin" ?

**Comment by McAtze** [comment]
Work in progress..

**Comment by Nirjonadda** [comment]
Great, How to adding this permissions? Do you adding in under General permissions or adding separate permissions?

**Comment by Nirjonadda** [comment]
@McAtze Where you are added permissions? I can not find out this permissions.

**Comment by McAtze** [comment]
You can find it under Forum, directly near attachment permissions..
