### ISSUE TITLE
Place the button inside the editor bar

### ISSUE THREAD

**Issue by Nirjonadda** [McAtze/-ITM-CheveretoIntegration#3]
Please add option "Place the button inside the editor bar" If not checked then use button below the editor bar.

![screenshot00144](https://user-images.githubusercontent.com/6899856/40845782-fb0c1a04-65b7-11e8-9f75-48458b5c9663.png)

**Comment by McAtze** [comment]
Implemented in v2.0.3

Please try it, test it and give feedback. There're some couriosities cause the dynamic of Editor JS. Use F5 to reloade the page.

**Comment by Nirjonadda** [comment]
Thanks, Great development improvement update.

**Comment by Nirjonadda** [comment]
@McAtze Please can be place this button after insert image button?

![screenshot00172](https://user-images.githubusercontent.com/6899856/41062808-2a56fc48-69d7-11e8-9483-cbb960823ac8.png)
