### ISSUE TITLE
Issue with button icon

### ISSUE THREAD

**Issue by Nirjonadda** [McAtze/-ITM-CheveretoIntegration#6]
Upload button icon are not showing correctly.

![screenshot00154](https://user-images.githubusercontent.com/6899856/40877794-ca26b5fa-6686-11e8-9f9d-449b7a3ee6ab.png)

**Comment by McAtze** [comment]
I need a link to reproduce this issue. For me it looks good.

![screenshot 2018-06-02 18 19 28](https://user-images.githubusercontent.com/8874582/40878443-8b9ec808-6691-11e8-8c68-31b6d200d5fe.png)

**Comment by Nirjonadda** [comment]
About Issue with button icon because we have not updated new JS files. So waiting for Chevereto v3.10.15 release.

Thanks
