### ISSUE TITLE
Upload button are not show

### ISSUE THREAD

**Issue by Nirjonadda** [McAtze/-ITM-CheveretoIntegration#7]
Upload button are not show if user have not permissions Upload attachments to posts.

**Comment by Nirjonadda** [comment]
I think this are not add-on issue, This issue happen from PUP Code. @McAtze Please can you confirm about this? Also I am going to report in [Chevereto support](https://chevereto.com/community/threads/upload-button-are-not-show.9971/) forum.

**Comment by McAtze** [comment]
You're right. The button position is handling from attachment button. If this one is missing the chevereto button is also missing.
